[package]
name = "corrosion"
version = "0.1.0"
authors = ["‚ä• team"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
